version: "3.2"

services:
  web:
    image: broyal/test-winauth-web:latest
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      placement:
          constraints: [node.platform.os == windows]
      labels:
        com.docker.ucp.mesh.http.80: "external_route=http://app.example.com,internal_port=80"
    networks:
        - ucp-hrm

networks:
    ucp-hrm:
        external: true