version: "3.2"

services:
  web:
    image: broyal/samplefxapp-web:1.1
    environment:
      - API_HOSTNAME=api
    ports:
      - 80:80
    networks:
      - nat
    depends_on:
      - api
  api:
    image: broyal/samplefxapp-api:1.1
    networks:
      - nat

networks:
  nat:
    external:
      name: nat